name: miss-selfie
favicon: null
layout_spectrum: 0.10161084751598537
typography_spectrum: 0.020657909801229835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.25987082067877054
  lightness: 0.23060002038255334
  saturation: 0.6239843387156725
  rhythmicContrast: 0.38067307183519006
purpose: []
